VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "aBarConfig"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public barId As Integer     '龟琂竊计
Public barNumber As Integer '竊计э腹絏
Public mete As Integer
Public mete2 As Integer
Public keyMain As String
Public barLineQuantity As Integer '︽竊计秖
Public linebreak As Boolean  'true 竊传︽
