VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "oNoteHeadOptions"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public dir As String
Public headx As Double
Public extrax As Double
Public flag As String
Public dot As Integer
Public dotshiftx As Double
Public scale_ As Double
Public accidentalSlot As iArray
Public shouldExtendStem As Boolean
Public printAccidentals As Boolean

