VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "oRelativeOptions"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public typs As String
Public klass As String
Public Name As String
Public anchor As String      '"start" | "middle" | "end"
Public position As String
Public dime As Variant
Public pitch2 As Double
Public realWidth As Double
Public lineWidth As Double
Public thickness As Double
Public stemHeight As Double
Public scalex As Double
Public scaley As Double
Public top As Double
Public bottom As Double
Public height As Double
Public width As Double


