VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "vMetaTextInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public abc_copyright       As vCharRange
Public abc_creator       As vCharRange
Public abc_version       As vCharRange
Public abc_charset       As vCharRange
Public abc_edited_by       As vCharRange
Public author As vCharRange
Public book As vCharRange
Public composer As vCharRange
Public discography As vCharRange
Public footer As vCharRange
Public group As vCharRange
Public header As vCharRange
Public history As vCharRange
Public instruction As vCharRange
Public notes As vCharRange
Public origin As vCharRange
Public partOrder As vCharRange
Public rhythm As vCharRange
Public source As vCharRange
Public tempo As vCharRange
Public textBlock As vCharRange
Public title As vCharRange
Public transcription As vCharRange
Public unalignedWords As vCharRange
Public url As vCharRange
