VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "vMetaText"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public abc_copyright As String
Public abc_creator As String
Public abc_version As String
Public abc_charset As String
Public abc_edited_by As String
Public author As String
Public book As String
Public composer As String
Public decorationPlacement As String     'Placement
Public discography As String
Public footer As Dictionary
Public group As String
Public header As Dictionary
Public history As String
Public instruction As String
Public measurebox As Boolean
Public notes As String
Public origin As String
Public partOrder As String
Public rhythm As String
Public source As String
Public tempo As vtempoProperties
Public textBlock As String
Public title As String
Public transcription As String
Public unalignedWords As iArray
Public url As String
