VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "vSpacingRenderer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public composer As Double
Public graceBefore As Double
Public graceInside As Double
Public graceAfter As Double
Public info As Double
Public lineSkipFactor As Double
Public music As Double
Public paragraphSkipFactor As Double
Public parts As Double
Public slurHeight As Double
Public staffSeparation As Double
Public stemHeight As Double
Public subtitle As Double
Public systemStaffSeparation As Double
Public text As Double
Public title As Double
Public top As Double
Public vocal As Double
Public words As Double
